
package com.suqc.ws.kspace;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUtilService", targetNamespace = "http://service.iutil.kspace.cnki.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IUtilService {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "batchImport", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.BatchImport")
    @ResponseWrapper(localName = "batchImportResponse", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.BatchImportResponse")
    public void batchImport(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "exportItem", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.ExportItem")
    @ResponseWrapper(localName = "exportItemResponse", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.ExportItemResponse")
    public String exportItem(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<String> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "exportAllItem", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.ExportAllItem")
    @ResponseWrapper(localName = "exportAllItemResponse", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.ExportAllItemResponse")
    public byte[] exportAllItem(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<String> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTemplateByCtype", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.GetTemplateByCtype")
    @ResponseWrapper(localName = "getTemplateByCtypeResponse", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.GetTemplateByCtypeResponse")
    public String getTemplateByCtype(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "importFullText", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.ImportFullText")
    @ResponseWrapper(localName = "importFullTextResponse", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.ImportFullTextResponse")
    public void importFullText(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        byte[] arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkRepeat", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.CheckRepeat")
    @ResponseWrapper(localName = "checkRepeatResponse", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.CheckRepeatResponse")
    public String checkRepeat(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEPersons", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.GetEPersons")
    @ResponseWrapper(localName = "getEPersonsResponse", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.GetEPersonsResponse")
    public String getEPersons(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContentType", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.GetContentType")
    @ResponseWrapper(localName = "getContentTypeResponse", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.GetContentTypeResponse")
    public String getContentType();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSystemDicts", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.GetSystemDicts")
    @ResponseWrapper(localName = "getSystemDictsResponse", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.GetSystemDictsResponse")
    public String getSystemDicts(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkFullTextRepeat", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.CheckFullTextRepeat")
    @ResponseWrapper(localName = "checkFullTextRepeatResponse", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.CheckFullTextRepeatResponse")
    public boolean checkFullTextRepeat(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEPersonDicts", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.GetEPersonDicts")
    @ResponseWrapper(localName = "getEPersonDictsResponse", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.GetEPersonDictsResponse")
    public String getEPersonDicts(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComms", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.GetComms")
    @ResponseWrapper(localName = "getCommsResponse", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.GetCommsResponse")
    public String getComms(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFullTextPath", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.GetFullTextPath")
    @ResponseWrapper(localName = "getFullTextPathResponse", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.GetFullTextPathResponse")
    public String getFullTextPath(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCommDicts", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.GetCommDicts")
    @ResponseWrapper(localName = "getCommDictsResponse", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.GetCommDictsResponse")
    public String getCommDicts(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service.iutil.kspace.cnki.org/", className = "com.suqc.ws.kspace.LoginResponse")
    public String login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
