
package com.suqc.ws.kspace;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IUtilServiceService", targetNamespace = "http://service.iutil.kspace.cnki.org/", wsdlLocation = "http://127.0.0.1:8080/kspace-oai/ws/importService?wsdl")
public class IUtilServiceService
    extends Service
{

    private final static URL IUTILSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException IUTILSERVICESERVICE_EXCEPTION;
    private final static QName IUTILSERVICESERVICE_QNAME = new QName("http://service.iutil.kspace.cnki.org/", "IUtilServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/kspace-oai/ws/importService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IUTILSERVICESERVICE_WSDL_LOCATION = url;
        IUTILSERVICESERVICE_EXCEPTION = e;
    }

    public IUtilServiceService() {
        super(__getWsdlLocation(), IUTILSERVICESERVICE_QNAME);
    }

    public IUtilServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IUTILSERVICESERVICE_QNAME, features);
    }

    public IUtilServiceService(URL wsdlLocation) {
        super(wsdlLocation, IUTILSERVICESERVICE_QNAME);
    }

    public IUtilServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IUTILSERVICESERVICE_QNAME, features);
    }

    public IUtilServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IUtilServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IUtilService
     */
    @WebEndpoint(name = "IUtilServicePort")
    public IUtilService getIUtilServicePort() {
        return super.getPort(new QName("http://service.iutil.kspace.cnki.org/", "IUtilServicePort"), IUtilService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IUtilService
     */
    @WebEndpoint(name = "IUtilServicePort")
    public IUtilService getIUtilServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.iutil.kspace.cnki.org/", "IUtilServicePort"), IUtilService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IUTILSERVICESERVICE_EXCEPTION!= null) {
            throw IUTILSERVICESERVICE_EXCEPTION;
        }
        return IUTILSERVICESERVICE_WSDL_LOCATION;
    }

}
