
package com.suqc.ws.cscy;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.18
 * 2018-01-15T16:14:48.662+08:00
 * Generated source version: 2.7.18
 */

@WebFault(name = "Exception", targetNamespace = "http://service.cscy.webservice.kspace.cnki.org/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.suqc.ws.cscy.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.suqc.ws.cscy.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.suqc.ws.cscy.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.suqc.ws.cscy.Exception getFaultInfo() {
        return this.exception;
    }
}
