package com.suqc.ws.cscy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2018-01-15T16:14:48.720+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://service.cscy.webservice.kspace.cnki.org/", name = "ICscyService")
@XmlSeeAlso({ObjectFactory.class})
public interface ICscyService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendApplyResult", targetNamespace = "http://service.cscy.webservice.kspace.cnki.org/", className = "com.suqc.ws.cscy.SendApplyResult")
    @WebMethod
    @ResponseWrapper(localName = "sendApplyResultResponse", targetNamespace = "http://service.cscy.webservice.kspace.cnki.org/", className = "com.suqc.ws.cscy.SendApplyResultResponse")
    public java.lang.String sendApplyResult(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        byte[] arg3
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCommList", targetNamespace = "http://service.cscy.webservice.kspace.cnki.org/", className = "com.suqc.ws.cscy.GetCommList")
    @WebMethod
    @ResponseWrapper(localName = "getCommListResponse", targetNamespace = "http://service.cscy.webservice.kspace.cnki.org/", className = "com.suqc.ws.cscy.GetCommListResponse")
    public java.lang.String getCommList();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getpdf", targetNamespace = "http://service.cscy.webservice.kspace.cnki.org/", className = "com.suqc.ws.cscy.Getpdf")
    @WebMethod
    @ResponseWrapper(localName = "getpdfResponse", targetNamespace = "http://service.cscy.webservice.kspace.cnki.org/", className = "com.suqc.ws.cscy.GetpdfResponse")
    public byte[] getpdf(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getReportId", targetNamespace = "http://service.cscy.webservice.kspace.cnki.org/", className = "com.suqc.ws.cscy.GetReportId")
    @WebMethod
    @ResponseWrapper(localName = "getReportIdResponse", targetNamespace = "http://service.cscy.webservice.kspace.cnki.org/", className = "com.suqc.ws.cscy.GetReportIdResponse")
    public java.lang.String getReportId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getApply", targetNamespace = "http://service.cscy.webservice.kspace.cnki.org/", className = "com.suqc.ws.cscy.GetApply")
    @WebMethod
    @ResponseWrapper(localName = "getApplyResponse", targetNamespace = "http://service.cscy.webservice.kspace.cnki.org/", className = "com.suqc.ws.cscy.GetApplyResponse")
    public java.lang.String getApply(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getApplyDetail", targetNamespace = "http://service.cscy.webservice.kspace.cnki.org/", className = "com.suqc.ws.cscy.GetApplyDetail")
    @WebMethod
    @ResponseWrapper(localName = "getApplyDetailResponse", targetNamespace = "http://service.cscy.webservice.kspace.cnki.org/", className = "com.suqc.ws.cscy.GetApplyDetailResponse")
    public java.lang.String getApplyDetail(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateApplyStatus", targetNamespace = "http://service.cscy.webservice.kspace.cnki.org/", className = "com.suqc.ws.cscy.UpdateApplyStatus")
    @WebMethod
    @ResponseWrapper(localName = "updateApplyStatusResponse", targetNamespace = "http://service.cscy.webservice.kspace.cnki.org/", className = "com.suqc.ws.cscy.UpdateApplyStatusResponse")
    public java.lang.String updateApplyStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "toLogin", targetNamespace = "http://service.cscy.webservice.kspace.cnki.org/", className = "com.suqc.ws.cscy.ToLogin")
    @WebMethod
    @ResponseWrapper(localName = "toLoginResponse", targetNamespace = "http://service.cscy.webservice.kspace.cnki.org/", className = "com.suqc.ws.cscy.ToLoginResponse")
    public java.lang.String toLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
