package com.suqc.ws.cscy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2018-01-15T16:14:48.741+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "ICscyServiceService", 
                  wsdlLocation = "http://127.0.0.1:8080/kspace-jspui/ws/icscyService?wsdl",
                  targetNamespace = "http://service.cscy.webservice.kspace.cnki.org/") 
public class ICscyServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.cscy.webservice.kspace.cnki.org/", "ICscyServiceService");
    public final static QName ICscyServicePort = new QName("http://service.cscy.webservice.kspace.cnki.org/", "ICscyServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/kspace-jspui/ws/icscyService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ICscyServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/kspace-jspui/ws/icscyService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ICscyServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ICscyServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ICscyServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ICscyServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ICscyServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ICscyServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ICscyService
     */
    @WebEndpoint(name = "ICscyServicePort")
    public ICscyService getICscyServicePort() {
        return super.getPort(ICscyServicePort, ICscyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICscyService
     */
    @WebEndpoint(name = "ICscyServicePort")
    public ICscyService getICscyServicePort(WebServiceFeature... features) {
        return super.getPort(ICscyServicePort, ICscyService.class, features);
    }

}
