
package com.suqc.ws.cxffile;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FileWS", targetNamespace = "http://impl.service.ws.suqc.com/file")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileWS {


    /**
     * 
     * @param file
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "upload", targetNamespace = "http://impl.service.ws.suqc.com/file", className = "com.suqc.ws.cxffile.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://impl.service.ws.suqc.com/file", className = "com.suqc.ws.cxffile.UploadResponse")
    public boolean upload(
        @WebParam(name = "file", targetNamespace = "")
        CxfFileWrapper file);

    /**
     * 
     * @return
     *     returns com.suqc.ws.cxffile.CxfFileWrapper
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "download", targetNamespace = "http://impl.service.ws.suqc.com/file", className = "com.suqc.ws.cxffile.Download")
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "http://impl.service.ws.suqc.com/file", className = "com.suqc.ws.cxffile.DownloadResponse")
    public CxfFileWrapper download();

}
